name = "twitter-blocker-backend"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "twitter-blocker-db"
database_id = "6e6921e2-72ff-416f-82cb-fc3e51619f48"
